### ISSUE TITLE
error

### ISSUE THREAD

**Issue by world4jason** [lamhiutung/Cityscapes#1]
in cityscapes.py 

        image_dir = "{}/{}".format(DATA_DIR, self.subset)
        image_ids = os.listdir(image_dir)
        for index, item in enumerate(image_ids):
            temp_image_path = "{}/{}".format(image_dir, item)
            temp_image_size = skimage.io.imread(temp_image_path).shape
            self.add_image("cityscape", image_id=index, gt_id=os.path.splitext(item)[0],
                            height=temp_image_size[0], width=temp_image_size[1],
                            path=temp_image_path)
if the DATA_DIR is '../data/leftImg8bit'
than image_ids is 
        ['bochum', 'aachen', 'hamburg', 'tubingen', 'zurich', 'ulm', 'weimar', 'cologne', 'erfurt', 'strasbourg', 'monchengladbach', 'hanover', 'jena', 'stuttgart', 'krefeld', 'bremen', 'darmstadt', 'dusseldorf']

so the temp_image_path might be something like...~/ROOT_DIR/data/leftImg8bit/train/bochum
but not the path to the image

and the program stuck.

**Comment by lamhiutung** [comment]
@world4jason 
I'm sorry I have not logged in for a long time.
Thanks for your issue, I am sorry I forgot to write down this step in README: 
Extract all pictures in the subfolders like 'bochum', 'aachen'... after downloading the data, 
and put them in the corresponding image_dir like **data/leftImg8bit/train**,
 so the temp_image_path would be something like **data/leftImg8bit/train/aachen_000000_000019.png**
